### ISSUE TITLE
Solution of [500 Library path /libraries/framework cannot be found.] in Joomla 3.4

### ISSUE THREAD

**Issue by asika32764** [asikart/userxtd#23]
Joomla 3.4 has removed `/libraries/framework` folder so caused this error.

Just create an empty folder at Joomla `/libraries/framework`, then everything will working well.

Please wait our next release to fix this issue.

**Comment by ribo72** [comment]
hello, i created the folder framework inside the folder libraries and remove this error.
just i want to inform you that in backend you can t handle users,profiles and fields.
you can handle only category

**Comment by ribo72** [comment]
i show you this image to see.
![new](https://cloud.githubusercontent.com/assets/7744474/6458915/cef1c176-c191-11e4-8236-3b35fd1f1914.JPG)

**Comment by asika32764** [comment]
Could you go to Global configuration and change `Error Display` to
`Development`, and return to this page?

If there has some error message shows, please get a screenshot for me

thank you

2015-03-03 16:41 GMT+08:00 ribo72 <notifications@github.com>:

> i show you this image to see.
> [image: new]
> <https://cloud.githubusercontent.com/assets/7744474/6458915/cef1c176-c191-11e4-8236-3b35fd1f1914.JPG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asikart/userxtd/issues/23#issuecomment-76906677>.
>



-- 
Best Regard

Simon Asika | Kwang Po Tung | 董冠伯
------------------------------------------------
- Founder: Asikart Extension <http://ext.asikart.com/>
- CTO: SMS Taiwan <http://www.bm-sms.com.tw/>

- Mobile: 886-928-565-747
- Github: https://github.com/asika32764

**Comment by ribo72** [comment]
Fatal error: Call to undefined method Joomla\String\String::unicode_to_utf8() in /libraries/vendor/joomla/registry/src/Format/Json.php on line 33
Am i missing something to my server?

**Comment by ribo72** [comment]
also tryed to install vrsion 1.0.0 local in another joomla 3.4 and gives 
Error
No file selected.

Unable to find install package

**Comment by asika32764** [comment]
I didn't meet this error.

I'll try to install it in a empty Joomla to test

ribo72 <notifications@github.com> 於 2015年3月3日 星期二寫道：

> Fatal error: Call to undefined method
> Joomla\String\String::unicode_to_utf8() in
> /libraries/vendor/joomla/registry/src/Format/Json.php on line 33
> Am i missing something to my server?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asikart/userxtd/issues/23#issuecomment-76924167>.
>


-- 
Best Regard

Simon Asika | Kwang Po Tung | 董冠伯
------------------------------------------------
- Founder: Asikart Extension <http://ext.asikart.com/>
- CTO: SMS Taiwan <http://www.bm-sms.com.tw/>

- Mobile: 886-928-565-747
- Github: https://github.com/asika32764

**Comment by ribo72** [comment]
i show in my server in phpinfo
json support	enabled
json version	1.2.1

**Comment by asika32764** [comment]
I think it is an error caused by Joomla framework.

I need to upgrade it to newest. Please wait our next release.

ribo72 <notifications@github.com> 於 2015年3月3日 星期二寫道：

> i show in my server in phpinfo
> json support enabled
> json version 1.2.1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asikart/userxtd/issues/23#issuecomment-76926664>.
>


-- 
Best Regard

Simon Asika | Kwang Po Tung | 董冠伯
------------------------------------------------
- Founder: Asikart Extension <http://ext.asikart.com/>
- CTO: SMS Taiwan <http://www.bm-sms.com.tw/>

- Mobile: 886-928-565-747
- Github: https://github.com/asika32764

**Comment by ribo72** [comment]
ok thank you

**Comment by maniot** [comment]
I upgraded joomla to version 3.4.0 and had the same problem, after creating the empty folder named framework in /libraries/ the problem was solved. the component and the plugin work as before without any other errors.
Thanks Asika 32764 for the solution, i realy like the component, great work.

**Comment by asika32764** [comment]
Should be fixed in 1.0.1

**Comment by pici65** [comment]
Hi,
in 1.0.1 is not fixed I have installed new version on 10 sites joomla 3.4 and the problem remain. Also I have tried to uninstall and re-install, the problem remain.

**Comment by SemaphoreOxalis** [comment]
I solved the issue with creating the fodler but after upgrading 3.4.1 the issue come back and the framework folder change nothing ! My clients are very angry...

**Comment by asika32764** [comment]
Are you install it in 3.4.0 or 3.4.1?

**Comment by pici65** [comment]
Yes, all the sites are in 3.4.1, all the sites gives
Key JLanguage has not been registered with the container. 
Happy Easter.

**Comment by asika32764** [comment]
There is another error in 3.4.1, please see: https://github.com/asikart/userxtd/issues/29#issuecomment-89574802 to download a hotfix of Windwalker to fix this error.

**Comment by pici65** [comment]
Many, many thanks for your fix.
Happy Easter to you and your family.

**Comment by ribo72** [comment]
thank you very much for the new fix. 
Happy Easter.
